---
# Defines deployment design and assigns role to server groups

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  sudo: True
  roles:
  - ceph-common

- hosts: mons
  sudo: True
  roles:
  - ceph-mon

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  vars:
    radosgw_server: "tengine"
    radosgw_tengine_url: "http://artifactory.tools.springer-sbm.com/spr-deb-release-local/pool/tengine_2.0.2-1_amd64.deb"
  roles:
  - ceph-radosgw
