---
## Prepare nginx
#

- name: Ensure nginx latest stable is installed
  apt: pkg=nginx state=latest update_cache=true
  notify:
    - restart nginx
  when: radosgw_manage_nginx

- name: Ensure the default site is removed
  file: path=/etc/nginx/sites-{{ item }}/default state=absent
  with_items:
    - enabled
    - available
  notify:
    - reload nginx
  when: radosgw_manage_nginx

- name: Ensure nginx is configured
  template: src=nginx_base.conf.j2 dest=/etc/nginx/nginx.conf group=root owner=root mode=0644
  notify:
    - reload nginx
  when: radosgw_manage_nginx

- name: Ensure nginx starts on a fresh reboot
  service: name=nginx state=started enabled=yes

- name: Ensure nginx ssl directory is created
  file: path=/etc/nginx/ssl state=directory
  when: radosgw_ssl

- name: Ensure nginx ssl certificate and key are created
  copy: src={{ nginx_ssl_local_path }}/{{ item }} dest=/etc/nginx/ssl/{{ item }} mode=0600
  with_items:
    - "{{ radosgw_ssl_cert_name }}"
    - "{{ radosgw_ssl_key_name }}"
  when: radosgw_ssl and radosgw_ssl_manage_certs
  notify:
    - reload nginx

## Prepare RGW
#
- name: Install Rados Gateway
  apt: >
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - radosgw

- name: Create RGW directory
  file: >
    path=/var/lib/ceph/radosgw/{{ ansible_fqdn }}
    state=directory
    owner=root
    group=root
    mode=0644

- name: Enable Rados Gateway vhost
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/radosgw.conf group=root owner=root mode=0644

- name: ensure sites-available is symlinked to sites-enabled
  file: src=/etc/nginx/sites-available/radosgw.conf dest=/etc/nginx/sites-enabled/radosgw.conf state=link
  notify:
  - reload nginx

## If we don't perform this check Ansible will start multiple instance of radosgw
- name: Check if RGW is started
  command: /etc/init.d/radosgw status
  register: rgwstatus
  ignore_errors: True

- name: Start RGW
  command: /etc/init.d/radosgw start
  when: rgwstatus.rc != 0

