---
- name: Copy RGW bootstrap key
  copy: src=fetch/{{ fsid }}/etc/ceph/keyring.radosgw.gateway dest=/etc/ceph/keyring.radosgw.gateway owner=root group=root mode=600
  when: cephx

- name: Set RGW bootstrap key permissions
  file: path=/etc/ceph/keyring.radosgw.gateway mode=0600 owner=root group=root
  when: cephx

## Check OS family
#

- include: install_redhat.yml
  when: (ansible_os_family == 'RedHat' and radosgw_server == 'apache')

- include: install_debian.yml
  when: (radosgw_server == 'apache' and ansible_os_family == 'Debian')

- include: install_nginx.yml
  when: radosgw_server == 'nginx'

- include: install_tengine.yml
  when: radosgw_server == 'tengine'
